const CAREPROVIDER = "CAREPROVIDER";
const CLIENT = "CLIENT";
const DIETICIAN = "DIETICIAN";
const TRAINER = "TRAINER";
const PHYSICIAN = "PHYSICIAN";

export { CAREPROVIDER, CLIENT, DIETICIAN, TRAINER, PHYSICIAN };
